version: "3.7"

volumes:
  portainer_data: {}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  #######################################
  # Nginx: web server
  #######################################
  nginx:
    image: nginx:latest
    container_name: lemp_nginx
    restart: always
    volumes:
      - ./www:/var/www/html
      # - ./nginx:/etc/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
      - ./nginx/certs:/etc/nginx/certs
      - /etc/localtime:/etc/localtime:ro
    #depends_on:
    # - api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
      - frontend

  #######################################
  # Redia: cache && session
  #######################################
  redis:
    image: redis
    container_name: lemp_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - backend

  #######################################
  # Mariadb: queue database
  #######################################
  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend

  #######################################
  # PHP: v7.3
  #######################################
  php73:
    build: ./php73
    container_name: lemp_php73-fpm
    restart: always
    volumes:
      - ./www:/var/www/html
      - ./php73/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php73/php.ini:/usr/local/etc/php/php.ini
      - ./logs/php73-fpm:/var/log/php-fpm
    expose:
      - "9000"
    networks:
      - backend

  #######################################
  # Portainer: docker management
  # user: admin: password: 12345678
  #######################################
  portainer:
    image: portainer/portainer
    container_name: lemp_portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks:
      - frontend
      # - backend
